Corrección de la entrega:

FFF......EEEEE
======================================================================
ERROR: test_propagacion_con_obstaculo (tests.test_semana_02.TestPropagar)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mlopez/.local/lib/python3.10/site-packages/timeout_decorator/timeout_decorator.py", line 82, in new_function
    return function(*args, **kwargs)
  File "/home/mlopez/git/homework-checker/01_getting_data/tests/test_semana_02.py", line 90, in test_propagacion_con_obstaculo
    self.assertEqual(semana_02.propagar([0, 0, 0, -1, 1, 0, 0, 0, -1, 0, 1, 0, 0]),
AttributeError: module 'semana_02' has no attribute 'propagar'

======================================================================
ERROR: test_propagacion_simple (tests.test_semana_02.TestPropagar)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mlopez/.local/lib/python3.10/site-packages/timeout_decorator/timeout_decorator.py", line 82, in new_function
    return function(*args, **kwargs)
  File "/home/mlopez/git/homework-checker/01_getting_data/tests/test_semana_02.py", line 86, in test_propagacion_simple
    self.assertEqual(semana_02.propagar([0, 0, 0, 1, 0, 0]), [1, 1, 1, 1, 1, 1])
AttributeError: module 'semana_02' has no attribute 'propagar'

======================================================================
ERROR: test_sin_fuego (tests.test_semana_02.TestPropagar)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mlopez/.local/lib/python3.10/site-packages/timeout_decorator/timeout_decorator.py", line 82, in new_function
    return function(*args, **kwargs)
  File "/home/mlopez/git/homework-checker/01_getting_data/tests/test_semana_02.py", line 99, in test_sin_fuego
    self.assertEqual(semana_02.propagar([0, 0, 0]), [0, 0, 0])
AttributeError: module 'semana_02' has no attribute 'propagar'

======================================================================
ERROR: test_todo_carbonizado (tests.test_semana_02.TestPropagar)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mlopez/.local/lib/python3.10/site-packages/timeout_decorator/timeout_decorator.py", line 82, in new_function
    return function(*args, **kwargs)
  File "/home/mlopez/git/homework-checker/01_getting_data/tests/test_semana_02.py", line 95, in test_todo_carbonizado
    self.assertEqual(semana_02.propagar([-1, -1, -1]), [-1, -1, -1])
AttributeError: module 'semana_02' has no attribute 'propagar'

======================================================================
ERROR: test_todo_encendido (tests.test_semana_02.TestPropagar)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mlopez/.local/lib/python3.10/site-packages/timeout_decorator/timeout_decorator.py", line 82, in new_function
    return function(*args, **kwargs)
  File "/home/mlopez/git/homework-checker/01_getting_data/tests/test_semana_02.py", line 103, in test_todo_encendido
    self.assertEqual(semana_02.propagar([1, 1, 1]), [1, 1, 1])
AttributeError: module 'semana_02' has no attribute 'propagar'

======================================================================
FAIL: test_basico (tests.test_semana_02.TestCollatz)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mlopez/.local/lib/python3.10/site-packages/timeout_decorator/timeout_decorator.py", line 82, in new_function
    return function(*args, **kwargs)
  File "/home/mlopez/git/homework-checker/01_getting_data/tests/test_semana_02.py", line 32, in test_basico
    self.assertEqual(semana_02.collatz(1), 0)
AssertionError: 1 != 0

======================================================================
FAIL: test_numeros_grandes (tests.test_semana_02.TestCollatz)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mlopez/.local/lib/python3.10/site-packages/timeout_decorator/timeout_decorator.py", line 82, in new_function
    return function(*args, **kwargs)
  File "/home/mlopez/git/homework-checker/01_getting_data/tests/test_semana_02.py", line 38, in test_numeros_grandes
    self.assertEqual(semana_02.collatz(27), 111)  # Número famoso en la conjetura
AssertionError: 42 != 111

======================================================================
FAIL: test_potencias_de_dos (tests.test_semana_02.TestCollatz)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mlopez/.local/lib/python3.10/site-packages/timeout_decorator/timeout_decorator.py", line 82, in new_function
    return function(*args, **kwargs)
  File "/home/mlopez/git/homework-checker/01_getting_data/tests/test_semana_02.py", line 43, in test_potencias_de_dos
    self.assertEqual(semana_02.collatz(16), 4)
AssertionError: 1 != 4

----------------------------------------------------------------------
Ran 14 tests in 0.010s

FAILED (failures=3, errors=5)

